version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./assets:/usr/share/nginx/assets
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
